"""

Revision ID: 1295c3f73a77
Revises: a831f16be8d6
Create Date: 2025-04-25 15:47:57.793186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1295c3f73a77'
down_revision = 'a831f16be8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_price', sa.Integer(), nullable=False))
        batch_op.drop_column('singleprice')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('singleprice', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('item_price')

    # ### end Alembic commands ###
