"""

Revision ID: 618d95524f5a
Revises: 14e1195634ee
Create Date: 2025-04-29 18:15:42.154780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618d95524f5a'
down_revision = '14e1195634ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
