"""

Revision ID: 993f43e1f080
Revises: 1295c3f73a77
Create Date: 2025-04-25 15:51:06.516546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993f43e1f080'
down_revision = '1295c3f73a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
