"""

Revision ID: ab3101e71564
Revises: f4232ee18c88
Create Date: 2025-04-24 15:23:00.729656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3101e71564'
down_revision = 'f4232ee18c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
