"""update order,payment_model

Revision ID: ad61934afa06
Revises: 9243e640dcbe
Create Date: 2025-04-30 14:55:27.243248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad61934afa06'
down_revision = '9243e640dcbe'
branch_labels = None
depends_on = None


    # ### commands auto generated by Alembic - please adjust! ###
   
       

