"""

Revision ID: c095b0e76613
Revises: cc4da0b14f4c
Create Date: 2025-04-25 15:14:12.079603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c095b0e76613'
down_revision = 'cc4da0b14f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_discount_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('after_discount_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grand_total', sa.Float(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('grand_total')
        batch_op.drop_column('after_discount_price')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('before_discount_price')

    # ### end Alembic commands ###
