"""drop_delivery_table

Revision ID: c12f8d04d30e
Revises: 0bb249cdcff1
Create Date: 2025-05-01 18:30:45.858187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12f8d04d30e'
down_revision = '0bb249cdcff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
