"""update_order_table

Revision ID: fee9baa541a5
Revises: c12f8d04d30e
Create Date: 2025-05-01 19:05:15.492078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee9baa541a5'
down_revision = 'c12f8d04d30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.alter_column('delivery_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullablee=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('delivery_status',
               existing_type=sa.VARCHAR(),
               nullablee=True)
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
